#!/usr/bin/env bash
# This script transfers a file from the client to a remote server using scp.

# Display usage if less than 4 parameters are provided
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Extract parameters
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Disable strict host key checking
scp_command="scp -o StrictHostKeyChecking=no -i $ssh_key $file_path $username@$server_ip:~/"

# Transfer the file using scp
$scp_command

# Check if scp command was successful
if [ $? -eq 0 ]; then
  echo "File transfer successful."
else
  echo "File transfer failed."
fi
