#!/usr/bin/env bash
# This script installs Nginx on an Ubuntu machine and configures it.

# Install nginx with '-y' flag to automatically answer yes to prompts
apt-get update
apt-get install -y nginx

# Configure nginx to listen on port 80 and return "Hello World!" on the root path
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Reload nginx configuration to apply changes
nginx -s reload
