#!/usr/bin/env bash
# This script configures Nginx for a custom 404 page.

# Check if user is running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run this script as root."
  exit 1
fi

# Install nginx with '-y' flag to automatically answer yes to prompts
apt-get update
apt-get install -y nginx

# Create a custom 404 error page configuration file
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    
    error_page 404 /custom_404.html;
    
    location = /custom_404.html {
        internal;
        root /var/www/html;
        echo 'Ceci n\'est pas une page';
    }
}" > /etc/nginx/sites-available/custom_404

# Enable the custom 404 site
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Remove default site configuration
rm /etc/nginx/sites-enabled/default

# Reload nginx configuration to apply changes
nginx -s reload
