#!/usr/bin/env bash
# Bash (init) script to manage manage_my_process.

case "$1" in
  start|stop|restart)
    sudo ./manage_my_process "$1"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
