#!/usr/bin/env bash
# This script displays the PID and process name of processes whose names contain the word "bash".

for pid in /proc/*/; do
  pid=${pid%*/}
  pid=${pid##*/}
  if [[ -f "/proc/$pid/cmdline" ]]; then
    cmdline=$(tr '\0' ' ' < "/proc/$pid/cmdline")
    if [[ $cmdline == *bash* ]]; then
      echo "$pid $(basename "$cmdline")"
    fi
  fi
done
