#!/usr/bin/env bash
# This script kills the process 7-highlander.

# Find the PID of the 7-highlander process
pid=$(pgrep -f "7-highlander")

# Check if the process is running
if [[ -n "$pid" ]]; then
  echo "Killing 7-highlander process..."
  # Kill the process
  kill "$pid"
else
  echo "7-highlander process is not running"
fi
