#!/usr/bin/env bash
# This script displays the content of the current directory in a list format, excluding hidden files, and displaying only the part of the name after the first dash

for file in *; do
    if [[ -f $file && ! $file == .* ]]; then
        name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name"
    fi
done
