#!/usr/bin/env bash
# Bash script to configure Nginx to run as nginx user and listen on port 8080

# Stop Nginx service if it's running
nginx -s stop

# Modify Nginx configuration to run as nginx user and listen on port 8080
sed -i 's/user\s*nginx;/user nginx;\n    listen 8080;/g' /etc/nginx/nginx.conf

# Start Nginx service
nginx
